// export const MODULES = {
//   DASHBOARD: "DASHBOARD",
//   DEPARTMENT: "DEPARTMENT",
//   STAFF: "STAFF",
//   ATTENDANCE: "ATTENDANCE",
//   PAYROLL: "PAYROLL",
//   LEAVES: "LEAVES",
//   LOAN: "LOAN",
//   CASHBOOK: "CASHBOOK",
//   REPORTS: "REPORTS",
//   ANNOUNCEMENTS: "ANNOUNCEMENTS",
//   SETTINGS: "SETTINGS",
// };
