// export const PERMISSIONS = {
//   // Dashboard
//   DASHBOARD_VIEW: "DASHBOARD_VIEW",

//   // Department
//   DEPARTMENT_VIEW: "DEPARTMENT_VIEW",
//   DEPARTMENT_CREATE: "DEPARTMENT_CREATE",
//   DEPARTMENT_EDIT: "DEPARTMENT_EDIT",
//   DEPARTMENT_DELETE: "DEPARTMENT_DELETE",

//   // Staff
//   STAFF_VIEW: "STAFF_VIEW",
//   STAFF_CREATE: "STAFF_CREATE",
//   STAFF_EDIT: "STAFF_EDIT",
//   STAFF_DELETE: "STAFF_DELETE",

//   // Attendance
//   ATTENDANCE_VIEW_SELF: "ATTENDANCE_VIEW_SELF",
//   ATTENDANCE_VIEW_TEAM: "ATTENDANCE_VIEW_TEAM",
//   ATTENDANCE_VIEW_ALL: "ATTENDANCE_VIEW_ALL",
//   ATTENDANCE_EDIT: "ATTENDANCE_EDIT",
//   ATTENDANCE_START_WORK: "ATTENDANCE_START_WORK",
//   ATTENDANCE_START_BREAK: "ATTENDANCE_START_BREAK",
//   ATTENDANCE_END_BREAK: "ATTENDANCE_END_BREAK",
//   ATTENDANCE_PUNCH_IN: "ATTENDANCE_PUNCH_IN",
//   ATTENDANCE_PUNCH_OUT: "ATTENDANCE_PUNCH_OUT",

//   // Payroll
//   PAYROLL_VIEW: "PAYROLL_VIEW",
//   PAYROLL_PROCESS: "PAYROLL_PROCESS",

//   // Leaves
//   LEAVE_APPLY: "LEAVE_APPLY",
//   LEAVE_APPROVE: "LEAVE_APPROVE",

//   // Loan
//   LOAN_APPLY: "LOAN_APPLY",
//   LOAN_APPROVE: "LOAN_APPROVE",

//   // Cashbook
//   CASHBOOK_VIEW: "CASHBOOK_VIEW",
//   CASHBOOK_EDIT: "CASHBOOK_EDIT",

//   // Reports
//   REPORT_VIEW: "REPORT_VIEW",
//   REPORT_DOWNLOAD: "REPORT_DOWNLOAD",

//   // Announcements
//   ANNOUNCEMENT_VIEW: "ANNOUNCEMENT_VIEW",
//   ANNOUNCEMENT_CREATE: "ANNOUNCEMENT_CREATE",

//   // Settings
//   SETTINGS_VIEW: "SETTINGS_VIEW",
//   SETTINGS_EDIT: "SETTINGS_EDIT",
// };
